baseurl=""
languageCode = "en-us"
title ="GrowMe"
theme="card"


[params]
  builtBy = "GrowMe"
  defaultImage = "FinalLogo.png"

  facebook = "https://www.facebook.com/groups/613384762947610/"
  instagram = "https://www.instagram.com/growme1012/"
  twitter = ""
  github = "https://github.com/GrowMe1012"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = "UA-174144473-1"
  disqus = ""

  [params.copyright]
     name = "GrowMe"
     link = "https://github.com/"